# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TradeRev-coding-challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TradeRev-coding-challenge
  
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper'

  target 'TradeRev-coding-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
