//
//  ParticularPhotoPresenter.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-10.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParticularPhotoPresentationLogic
{
  func presentSomething(response: ParticularPhoto.Response)
}

class ParticularPhotoPresenter: ParticularPhotoPresentationLogic
{
  weak var viewController: ParticularPhotoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ParticularPhoto.Response)
  {
    let viewModel = ParticularPhoto.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
