//
//  ParticularPhotoRouter.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-10.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ParticularPhotoRoutingLogic
{
  func routeToPhotGrid()
}

protocol ParticularPhotoDataPassing
{
  var dataStore: ParticularPhotoDataStore? { get set }
}

class ParticularPhotoRouter: NSObject, ParticularPhotoRoutingLogic, ParticularPhotoDataPassing
{
  weak var viewController: ParticularPhotoViewController?
  var dataStore: ParticularPhotoDataStore?
  
  // MARK: Routing
  
  func routeToPhotGrid() {
    guard let rootController = (UIApplication.shared.delegate as? AppDelegate)?.window?.rootViewController as? UINavigationController else {
      Log.error("FAILED TO LOAD ROOT CONTROLLER")
      return
    }
    
    guard let photoGridVC = rootController.viewControllers.first as? PhotoGridViewController else {
      Log.error("CAN\'T REACH PHOTO GRID CONTROLLER")
      return
    }
  
    let ip = IndexPath(row: dataStore?.currentIndex ?? 0, section: 0)
    let rect = photoGridVC.collectionView?.layoutAttributesForItem(at: ip)?.frame
    photoGridVC.collectionView?.scrollRectToVisible(rect!, animated: false)
  }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ParticularPhotoViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ParticularPhotoDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
