//
//  ParticularPhotoInteractor.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-10.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParticularPhotoBusinessLogic
{
  func doSomething(request: ParticularPhoto.Request)
}

protocol ParticularPhotoDataStore
{
  //var name: String { get set }
}

class ParticularPhotoInteractor: ParticularPhotoBusinessLogic, ParticularPhotoDataStore
{
  var presenter: ParticularPhotoPresentationLogic?
  
  // MARK: Do something
  
  func doSomething(request: ParticularPhoto.Request)
  {
    let response = ParticularPhoto.Response()
    presenter?.presentSomething(response: response)
  }
}
