//
//  LoginRouter.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-08.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToPhotoGrid()
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToPhotoGrid() {
    guard let _ = UIApplication.shared.instantiateAndShow(controllerID: "PhotoGridViewControllerID") else {
      viewController?.displayError(Login.LoginError(err: IVError(desc: "FAILED TO LOAD VIEW CONTROLLER USING \"PhotoGridViewControllerID\" as ID")))
      return
    }
  }
}
