//
//  PhotoGridPresenter.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-09.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import UnsplashKit

protocol PhotoGridPresentationLogic
{
  func presentRefreshPhotos(_ indexes: CountableRange<Int>)
  func presentError(error: PhotoGrid.Error)
}

class PhotoGridPresenter: PhotoGridPresentationLogic
{
  weak var viewController: PhotoGridDisplayLogic?
  
  // MARK: Do something
    
  func presentError(error: PhotoGrid.Error)
  {
    DispatchQueue.main.async {
      self.viewController?.displayError(error)
    }
  }
  
  
  func presentRefreshPhotos(_ indexes: CountableRange<Int>) {
    DispatchQueue.main.async {
      self.viewController?.displayRefresh(indexes)
    }
  }
}
