//
//  PhotoGridPresenter.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-09.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoGridPresentationLogic
{
  func presentSomething(response: PhotoGrid.Something.Response)
}

class PhotoGridPresenter: PhotoGridPresentationLogic
{
  weak var viewController: PhotoGridDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PhotoGrid.Something.Response)
  {
    let viewModel = PhotoGrid.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
