//
//  PhotoGridModels.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-09.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import UnsplashKit

enum PhotoGrid
{
  // MARK: Use cases
  
  struct LoadDataRequet {
    let row: Int
  }
  struct Request
  {
  }
  struct Response
  {
    let photos:[Photo]
  }
  struct ViewModelProgress
  {
    let message: String
  }
  struct Error
  {
    let error: IVError
  }
}
