//
//  PhotoGridInteractor.swift
//  ImageViewer
//
//  Created by Zakhar Sukhanov on 2017-12-09.
//  Copyright (c) 2017 Zakhar Sukhanov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoGridBusinessLogic
{
  func doSomething(request: PhotoGrid.Something.Request)
}

protocol PhotoGridDataStore
{
  //var name: String { get set }
}

class PhotoGridInteractor: PhotoGridBusinessLogic, PhotoGridDataStore
{
  var presenter: PhotoGridPresentationLogic?
  var worker: PhotoGridWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PhotoGrid.Something.Request)
  {
    worker = PhotoGridWorker()
    worker?.doSomeWork()
    
    let response = PhotoGrid.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
